name: Stable

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: gitea
          settings-path: ${{ gitea.workspace }}

      - name: Build with Maven
        run: mvn -B package -s $GITEA_WORKSPACE/.gitea/workflows/settings.xml --file pom.xml
        env:
          ACCESS_TOKEN: ${{ secrets.GITEA_TOKEN }}
          OWNER: ${{ gitea.repository_owner }}
          REPO_NAME: ${{ gitea.repository.name }}

      - name: Publish to Gitea Packages (Maven)
        run: mvn deploy -s $GITEA_WORKSPACE/.gitea/workflows/settings.xml
        env:
          ACCESS_TOKEN: ${{ secrets.GITEA_TOKEN }}
          OWNER: ${{ gitea.repository_owner }}
          REPO_NAME: ${{ gitea.repository.name }}
